apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd
  namespace: flux-system

spec:
  interval: 1m

  url: https://github.com/devopsrakesh29/fluxcd.git

  ref:
    branch: main